sonar.sources=frontend/src, backend/src
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/.git/**, **/tsconfig.tsbuildinfo, **/package-lock.json, **/coverage/**

# Ignore the 'JSX element not internationalized' rule (S6847) globally
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6847
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
